// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmkpxyhuskdneirsjsaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtta3B4eWh1c2tkbmVpcnNqc2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODc5MTcsImV4cCI6MjA2MDU2MzkxN30.9XCCR4hL-yFEPskQt0obf-r2tIKuOAfVP7zeXE2R2Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);